logging:
  level:
    org.local.console: DEBUG

server:
  port: 8080

rocketmq:
  namesrv-addr: 127.0.0.1:9876
  broker-addr: 127.0.0.1:10911

spring:
  web:
    resources:
      static-locations: classpath:/static/
